# Task 1

In [2]:
import numpy as np

In [ ]:
array_1D = np.array([1,2,3,4,5,6,7,8,9,10])
print(array_1D)
arr_1D = np.arange(1,11)
arr_1D

[ 1  2  3  4  5  6  7  8  9 10]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
array_2D=np.array([[1,2,3,4,5,6,7,8,9]]).reshape(3,3)
array_2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
array = np.array([10,20,30,40,50])
array

array([10, 20, 30, 40, 50])

In [16]:
print(array_1D.shape)
print(arr_1D.shape)
print(array_2D.shape)
print(array.shape)

(10,)
(10,)
(3, 3)
(5,)


In [17]:
print(array_1D.dtype)
print(arr_1D.dtype)
print(array_2D.dtype)
print(array.dtype)

int64
int64
int64
int64


# Task 2

In [18]:
A = np.array([10,20,30,40])
B = np.array([1,2,3,4])

In [19]:
A+B

array([11, 22, 33, 44])

In [20]:
A-B

array([ 9, 18, 27, 36])

In [21]:
A*B

array([ 10,  40,  90, 160])

In [24]:
A/B

array([10., 10., 10., 10.])

In [25]:
A**2

array([ 100,  400,  900, 1600])

# Task 3

In [26]:
values = np.array([2,4,6,8,10])
values

array([ 2,  4,  6,  8, 10])

In [ ]:
print.("Square root:",np.sqrt(values))
print("Exponential:",np.exp(values))
print("Logarithm:",np.log(values))
print("Sum:",np.sum(values))
print("Cumulative Sum:",np.cumulative_sum(values))

Square root: [1.41421356 2.         2.44948974 2.82842712 3.16227766]
Exponential: [7.38905610e+00 5.45981500e+01 4.03428793e+02 2.98095799e+03
 2.20264658e+04]
Logarithm: [0.69314718 1.38629436 1.79175947 2.07944154 2.30258509]
Sum: 30
Cumulative Sum: [ 2  6 12 20 30]


# Task 4

In [36]:
data = np.array([[10,20,30],[40,50,60],[70,80,90]])
data

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [40]:
print("Row wise sum:",np.sum(data, axis=1))
print("Column wise sum:",np.sum(data, axis=0))

Row wise sum: [ 60 150 240]
Column wise sum: [120 150 180]


In [41]:
# min value
np.min(data)

np.int64(10)

In [42]:
# max value
np.max(data)

np.int64(90)

In [43]:
# overall mean
np.mean(data)

np.float64(50.0)

# Task 5

In [44]:
marks = np.array([78,85,90,66,72,88,95,60])
marks

array([78, 85, 90, 66, 72, 88, 95, 60])

In [51]:

print("Mean:",np.mean(marks))
print("Median:",np.median(marks))
print("Variance:",np.var(marks))
print("Standart Deviation",np.std(marks))
print("Min:",np.min(marks))
print("Max:",np.max(marks))
marks=np.sort(marks)[::-1]
marks


Mean: 79.25
Median: 81.5
Variance: 134.1875
Standart Deviation 11.583932838203095
Min: 60
Max: 95


array([95, 90, 88, 85, 78, 72, 66, 60])

# Task 6

In [53]:
marks = np.array([78,85,90,66,72,88,95,60])
marks

array([78, 85, 90, 66, 72, 88, 95, 60])

In [54]:
np.sort(marks)

array([60, 66, 72, 78, 85, 88, 90, 95])

In [55]:
np.percentile(marks,[25,50,75])

array([70.5, 81.5, 88.5])

In [67]:
ctr = 0
avgr=np.average(marks)
for i in marks:
    if i > avgr:
        ctr +=1
ctr

4

# Task 6

In [58]:
sales = np.array([1200,1500,900,2000,1800,1700,1600])
sales

array([1200, 1500,  900, 2000, 1800, 1700, 1600])

In [60]:
print("Total weekly sales:" ,np.sum(sales))

Total weekly sales: 10700


In [61]:
print("Average daily sales:", np.average(sales))

Average daily sales: 1528.5714285714287


In [62]:
print("Highest day sales:", np.max(sales))
print("Lowest day sales:", np.min(sales))

Highest day sales: 2000
Lowest day sales: 900


In [63]:
print("Standard deviation of sales:", np.std(sales))

Standard deviation of sales: 345.2298849598449


In [66]:
above_avg_sales = []
avgr=np.average(sales)
for i in sales:
    if i > avgr:
        above_avg_sales.append(i)
above_avg_sales

[np.int64(2000), np.int64(1800), np.int64(1700), np.int64(1600)]